version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /aports
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /archisteamfarm
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /base-alpine
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /base-travis
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /c3d2-bullshit-bingo
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /code-server
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /code-server-extra
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /firefly-iii
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /gitea-nginx
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /halcyon
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /healthchecks
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /images-weserv
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /iodine
    schedule:
  - package-ecosystem: docker
    directory: /kibitzr
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /mastodon-nginx
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /musicbot
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /musicbrainz
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /musicbrainz-postgres
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /open-web-calendar
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /prerenderer
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /privatebin
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /reddiscord
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /screeenly
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /thelounge
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /unbound
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /yourls
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /zeronet
    schedule:
      interval: daily
